# -*- coding: utf-8 -*-
"""проба пера.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sxk3rG9qk_E9s02bjc7JzEilXemjtcYG
"""

# без установки этой библиотеки в следующих командах не импортируется ничего

!pip install aiogram

# в интернете пишут, что для запуска нужен executor, а он в версии 2 aiogram только есть
!pip show aiogram

# bot.py
# config_py добавлен в файлы, там скопированный токен и строчка с DB_PATH.
# Почему-то файл в загрузках называется config_py.py
import asyncio
import logging
import sys

from aiogram import Bot,Dispatcher, types
from aiogram.client.default import DefaultBotProperties
from aiogram.enums import ParseMode
from aiogram.filters import CommandStart, Command
from aiogram.types import Message, BotCommand
from config.py import API_TOKEN



!cat config.py

dp=Dispatcher()

@dp.message(CommandStart())
async def command_start_hendler(message="start"):
  await message.answer("привет я бот")

@dp.message()
async def echo_handler(message:Message):
    await message.answer("привет еще раз")

async def main():
  bot=Bot(token=API_TOKEN)
  await dp.start_polling(bot)

# if __name__=="__main__": если писать строчку так, то выдается ошибка:
# RuntimeError: asyncio.run() cannot be called from a running event loop
# if __name__=="_main_": если убрать нижние пробелы у слова main, то код запускатется
# но бот все равно не работает. ничего не отвечает
# что мне делать? я несколько раз переделывала и ничего не выходит
if __name__=="_main_":
  logging.basicConfig(Level=logging.INFO, stream=sys.stdout)
  asyncio.run(main())